# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Mapping


LocaleMessages = Mapping[str, str]

_EN: dict[str, str] = {
    "html_lang": "en",
    "eyebrow": "ArtifactWeaver static report",
    "generated": "Generated",
    "conclusion": "Conclusion",
    "summary_metrics": "Summary Metrics",
    "markdown_narrative": "Markdown Narrative",
    "report_sections": "Report Sections",
    "evidence": "Evidence",
    "artifact_index": "Artifact Index",
    "scope_boundaries": "Scope And Boundaries",
    "source_of_truth": "Source of truth",
    "generated_view": "Generated view",
    "private_data_policy": "Private data policy",
    "exists": "Exists",
    "support_evidence": "Support evidence",
    "gameplay_oracle": "Gameplay oracle",
    "artifact_id": "ID",
    "label": "Label",
    "kind": "Kind",
    "path": "Path",
    "no_summary_metrics": "No summary metrics were provided.",
    "no_report_sections": "No report sections were provided.",
    "no_artifact_index": "No artifact index was provided.",
    "no_linked_evidence": "No linked evidence was provided.",
    "untitled_section": "Untitled section",
    "untitled_evidence": "Untitled evidence",
    "unknown": "unknown",
    "yes": "true",
    "no": "false",
    "footer": "Generated by ArtifactWeaver {version}. Licensed under Apache-2.0.",
}

_ZH_HANS: dict[str, str] = {
    "html_lang": "zh-Hans",
    "eyebrow": "ArtifactWeaver 静态报告",
    "generated": "生成时间",
    "conclusion": "结论",
    "summary_metrics": "汇总指标",
    "markdown_narrative": "Markdown 叙述",
    "report_sections": "报告分节",
    "evidence": "证据",
    "artifact_index": "产物索引",
    "scope_boundaries": "范围与边界",
    "source_of_truth": "事实来源",
    "generated_view": "生成视图",
    "private_data_policy": "私有数据策略",
    "exists": "存在",
    "support_evidence": "辅助证据",
    "gameplay_oracle": "玩法判定依据",
    "artifact_id": "ID",
    "label": "标签",
    "kind": "类型",
    "path": "路径",
    "no_summary_metrics": "未提供汇总指标。",
    "no_report_sections": "未提供报告分节。",
    "no_artifact_index": "未提供产物索引。",
    "no_linked_evidence": "未提供关联证据。",
    "untitled_section": "未命名分节",
    "untitled_evidence": "未命名证据",
    "unknown": "未知",
    "yes": "是",
    "no": "否",
    "footer": "由 ArtifactWeaver {version} 生成。使用 Apache-2.0 许可。",
}

_MESSAGES: dict[str, dict[str, str]] = {
    "en": _EN,
    "zh-Hans": _ZH_HANS,
}

_ZH_HANS_ALIASES = {
    "zh",
    "zh-cn",
    "zh-hans",
    "chinese",
    "simplified-chinese",
    "simplified chinese",
    "简体中文",
    "中文",
}

_STATUS_LABELS: dict[str, dict[str, str]] = {
    "en": {
        "pass": "Pass",
        "passed": "Passed",
        "fail": "Fail",
        "failed": "Failed",
        "gap": "Gap",
        "passed-with-gaps": "Passed with gaps",
        "inconclusive": "Inconclusive",
        "unknown": "unknown",
    },
    "zh-Hans": {
        "pass": "通过",
        "passed": "通过",
        "fail": "失败",
        "failed": "失败",
        "gap": "缺口",
        "passed-with-gaps": "通过但存在缺口",
        "inconclusive": "结论不足",
        "unknown": "未知",
    },
}


def resolve_locale(locale: str | None) -> tuple[str, LocaleMessages]:
    """Return a canonical renderer locale and message bundle.

    Missing and unsupported locales fall back to English for backward
    compatibility with existing manifests.
    """

    normalized = (locale or "").strip()
    normalized_key = normalized.replace("_", "-").casefold()
    if normalized_key in _ZH_HANS_ALIASES:
        return "zh-Hans", _MESSAGES["zh-Hans"]
    return "en", _MESSAGES["en"]


def label_status(value: object, locale: str) -> str:
    raw = str(value)
    labels = _STATUS_LABELS.get(locale, _STATUS_LABELS["en"])
    return labels.get(raw.casefold(), raw)


def label_bool(value: object, messages: LocaleMessages) -> str:
    if isinstance(value, bool):
        return messages["yes"] if value else messages["no"]
    return str(value)
